{
 "title": "ads",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Cumulation of tumbling windows - num ads per city",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time({topic=\"ads-by-city-and-year-tmbl-win\"} | unwrap num_ads | __error__=`` [12h])) by (city)",
     "legendFormat": "{{city}}"
    }
   ]
  },
  {
   "title": "Ads scraped over the last minute per city (sliding window)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "last_over_time({topic=\"ads-by-city-sld-win\"} | unwrap num_ads | __error__=`` [1m]) by (city)",
     "legendFormat": "{{city}}"
    }
   ]
  },
  {
   "title": "Cumulation of tumbling windows - num ads per city per year",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum(sum_over_time({topic=\"ads-by-city-and-year-tmbl-win\"} | unwrap num_ads | __error__=`` [1m])) by (posted_year,city)",
     "legendFormat": "{{city}}"
    }
   ]
  }
 ]
}